# default main used.
debug_log_filename: debugLog
logsLocation: file_location_create
percentage_filter_default: 25
repeat: true
repeatfileLocation: default_store_location
usefilepath: true
# stock method
max_price_threshold: 200
